export const PROJECTS_LIST = [
    {
        link: "https://lab.siwonschool.com/m/?s=products",
        img: "/images/bg_siwonlab.png",
        area: "WEBSITE",
        company: "시원스쿨 LAB",
        year: "©2024",
    },
    {
        link: "https://japan.siwonschool.com/?s=products&cate=3",
        img: "/images/bg_siwonjapan.png",
        area: "WEBSITE",
        company: "시원스쿨 일본어 맞춤강좌찾기",
        year: "©2024",
    },
    {
        link: "https://ggbaro.kr/web/index.do",
        img: "/images/bg_ggbaro.png",
        area: "WEBSITE",
        company: "경기도상권분석서비스",
        year: "©2023",
    },
    {
        link: "",
        img: "/images/bg_lgcns.png",
        area: "ADMIN SYSTEM",
        company: "LG 화학 ITMS 업무Portal 재구축",
        year: "©2022",
    },
    {
        link: "",
        img: "/images/bg_lges.png",
        area: "ADMIN SYSTEM",
        company: "LG에너지솔루션 ITMS 업무Portal 이관",
        year: "©2022",
    },
    {
        link: "",
        img: "/images/bg_korloy.png",
        area: "ADMIN SYSTEM",
        company: "KORLOY 견적 시스템 'KQS-2023 Project' ",
        year: "©2023",
    },
    {
        link: "",
        img: "/images/bg_mslk.png",
        area: "WEBSITE",
        company: "MSLINK&SOLUTION",
        year: "©2023",
    },
    {
        link: "",
        img: "/images/bg_nh.png",
        area: "ADMIN SYSTEM",
        company: "농협 고객행복센터 방화벽 교체 및 IT자산관리시스템 고도화",
        year: "©2023",
    },
    {
        link: "http://www.lawdw.com/",
        img: "/images/bg_lawdw.png",
        area: "WEBSITE",
        company: "법무법인 두우",
        year: "©2021",
    },
  ];